#!/bin/bash


force=$1
find jekyll/portfolio -type f -not -name "*thumb*" | while read file; do
  if ! grep -q 'Benjamin Feng' $file || [ -n "$force" ]; then
    convert "$file" -background white -flatten "$file" && \
    $BAKE -q crush "$file" 110
  fi
done
