name:      'fengb'
url:       'http://fengb.info'
author:    'Benjamin Feng'
permalink: '/blog/:year/:month/:day/:title.html'
exclude:   [config.ru, tmp]
assets:
  debug:         true
  js_compressor: uglifier
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
    - _assets/fonts
