#!/bin/bash


force=$1
find jekyll/samples -type f -not -name "*thumb*" | while read file; do
  target=`sed -e 's/.png$/-thumb.png/' <<<$file`
  if [ ! -e "$target" ] || [ -n "$force" ]; then
    convert -resize 'x150' "$file" png8:"$target"
    $BAKE image/crush "$target" 220
  fi
done
