#!/bin/bash


force=$1
find samples -type f -not -name "*thumb*" | while read file; do
  target=`sed -e 's/.png$/-thumb.png/' <<<$file`
  if [ ! -e "$target" ] || [ -n "$force" ]; then
    convert -resize 'x150' "$file" "$target"
    pngquant --force --ext .png "$target"
    pngcrush -rem gAMA -rem cHRM -rem iCCP -rem sRGB -rem text \
             -text b 'License' 'http://creativecommons.org/licenses/by-nc-nd/3.0/' \
             -text b 'Url'     'http://fengb.info' \
             -text b 'Author'  'Benjamin Feng' \
             -res 220 -ow "$target"
  fi
done
