#!/bin/bash


gitorigin=`git remote show -n origin | sed -e '/Fetch URL/!d' -e 's/ *Fetch URL: //'`

cd dist
git init
git add .
git commit -m "AUTO PUBLISH"

git remote add origin $gitorigin
git push -f origin master
